### ISSUE TITLE
Requires Twig Tweak or similar?

### ISSUE THREAD

**Issue by yakatz** [UMD-Digital/umd_terp#1]
Getting this error: `Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "drupal_menu" function." at /webroot/web/themes/contrib/umd_terp/templates/_includes/global/header.html.twig line 23`.
Able to get past it by enabling `twig_tweak` module.

**Comment by drogers98** [comment]
Yes, good catch. Unfortunately, we cannot yet "require" dependency on modules from themes, though it seems to be close: https://www.drupal.org/project/drupal/issues/474684

In the meantime 45060674376eebfc7f41abdfef87979e8ad0f1a1 adjusts the composer.json and adds documentation to the readme. 

We could likely remove the twig_tweak dependency entirely, likely, but at the moment we are low on time on the project
