### ISSUE TITLE
Unnecessary `require "vendor/autoload.php";`

### ISSUE THREAD

**Issue by yakatz** [UMD-Digital/umd_terp#2]
On initial theme activation:
`Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='/webroot/vendor/pear/archive_tar:/webroot/vendor/pear/console_getopt:/webroot/vendor/pear/pear-core-minimal/src:/webroot/vendor/pear/pear_exception:.:/opt/cpanel/ea-php73/root/usr/share/pear') in /webroot/web/themes/contrib/umd_terp/umd_terp.theme on line 8`

Removing the entire line `require "vendor/autoload.php";` resolves the issue.

Drupal 8.7.10

**Comment by drogers98** [comment]
This was a holdover from some previous requirements of a composer library.
Also removed the additional unused use statements, as they are now in their respective INC files.

Fixed with commit c6bd2627a2623fd3262ebb765c1ad138e3f19a6b
