### ISSUE TITLE
Global Header: Screenreader is reading "Gift Make a Gift"

### ISSUE THREAD

**Issue by auromita** [UMD-Digital/umd_terp#5]
#### The screen reader is reading "Gift Make A Gift" in the global header when focusing on "Make a Gift" area with the search bar.

This could be potentially confusing to the user. 

###### Screenshot Below:
<img width="130" alt="Screen Shot of 'Make a Gift' area" src="https://user-images.githubusercontent.com/67974395/88297523-00626880-ccce-11ea-9540-efbe0200dcf5.png">

**Comment by drogers98** [comment]
@auromita this will need to get addressed in the schoolwide header repo: https://github.com/UMD-Digital/umd_schoolwide_header as we cannot edit from here unfortunately.
