### ISSUE TITLE
Footer: Screenreader reading phone number as a very large number

### ISSUE THREAD

**Issue by auromita** [UMD-Digital/umd_terp#6]
#### On the footer, the phone number is being read as "three hundred and one point four hundred and five point one thousand" instead of individual numbers. 

This issue has been previously resolved on [Policies Project Phone Number Issue](https://github.com/UMD-Digital/policies-next/issues/6). Similar methods can be used to resolve this issue as well.

**Comment by magnessjo** [comment]
aria-label="3014051000"

**Comment by drogers98** [comment]
aria label added as specified by @magnessjo. Will be on 8.1.40 release.
