### ISSUE TITLE
Breadcrumbs: Screenreader reads ">" as greater than.

### ISSUE THREAD

**Issue by auromita** [UMD-Digital/umd_terp#7]
#### Breadcrumbs: The screen reader is reading breadcrumbs as "Home greater than Basic Pages". 

This is an example but applies to all breadcrumbs across the site. 

###### Screenshot Below: 
<img width="319" alt="Screenshot of Home to Basic Pages Breadcrumbs" src="https://user-images.githubusercontent.com/67974395/88299114-fd687780-cccf-11ea-9c43-1e85712eee2b.png">

**Comment by drogers98** [comment]
Recommend we have @anthonybarsotti replace ">" with a css shape.

**Comment by anthonybarsotti** [comment]
@drogers98 I just pushed an update for this, it now just uses an empty string in the before pseudo and instead uses CSS to create the shape of the ">".
