### ISSUE TITLE
Kitchen Sink: Tables need Titles

### ISSUE THREAD

**Issue by auromita** [UMD-Digital/umd_terp#9]
#### On [Kitchen Sink Tables Section](https://drupal8demos.umd.edu/kitchen-sink#tables) the tables do not have titles.
All tables should have titles so that the user knows what the table is about beforehand.
Example: Headings Table

###### Screenshot Below:
![image](https://user-images.githubusercontent.com/67974395/88330754-dcb51780-ccf9-11ea-903b-fa26b5c29f74.png)

**Comment by drogers98** [comment]
@auromita When you say "table title" do you mean a row that col spans all columns, and has a top-level TH, such as described here:https://its.temple.edu/creating-tables-html#1715 ?

I am not showing tables as being misinformed or failing any validations in either wave or siteimprove, nor do I see any documentation in wc3/etc stating they are required or encoraged.

Happy to adjust to whatever UMD wants, just want to ensure I am understanding the request.

**Comment by auromita** [comment]
@drogers98 my apologies, I realize this is not necessary. I think I was under the impression it was but just verified that it is not. I will close this issue.
